# Generated by Django 3.0.7 on 2020-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='amount_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='post_rating',
            field=models.IntegerField(default=0),
        ),
    ]
