# Generated by Django 3.0.7 on 2020-07-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200713_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
