# Generated by Django 3.0.8 on 2020-08-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='amount_of_comments',
            field=models.IntegerField(default=1),
        ),
    ]
