# Generated by Django 3.0.8 on 2020-08-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200804_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='lol',
            field=models.CharField(default='lol', max_length=120),
        ),
    ]
