# Generated by Django 3.0.8 on 2020-08-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200804_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='lol',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='mama',
        ),
    ]
