# Generated by Django 3.0.7 on 2020-07-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10)),
                ('karma', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
